defmodule CliMate.EmbedTest do
  alias CliMate.CLI
  alias CliMate.CLI.ProcessShell
  alias Mix.Tasks.Cli.Embed
  use ExUnit.Case, async: false

  @moduletag :tmp_dir

  setup %{tmp_dir: tmp_dir} do
    CLI.put_shell(ProcessShell)
    cwd = File.cwd!()
    File.cd!(tmp_dir)
    on_exit(fn -> File.cd!(cwd) end)
    :ok
  end

  defp embed(argv) do
    Embed.run(argv)
    flush_output()
  end

  defp check(argv \\ []) do
    Embed.Check.run(argv)
    flush_output()
  end

  defp flush_output(lines \\ [], halt \\ nil) do
    receive do
      {:cli_mate_shell, :halt, code} -> flush_output(lines, code)
      {:cli_mate_shell, _kind, message} -> flush_output([message | lines], halt)
    after
      0 -> {lines |> Enum.reverse() |> Enum.join("\n"), halt}
    end
  end

  defp replace_banner(path, banner) do
    code = path |> File.read!() |> CliMate.Embed.strip_banner()
    File.write!(path, banner <> code)
  end

  describe "cli.embed" do
    test "replaces CliMate.CLI references in docs" do
      embed(~w(App.CLI lib/app/cli -fy))

      for path <- Path.wildcard("lib/app/**/*.ex") do
        refute File.read!(path) =~ "CliMate.CLI"
      end

      assert File.read!("lib/app/cli/argument.ex") =~ "iex> App.CLI.Argument.new(:lang, [])"
    end

    test "--skip-docs and --no-moduledoc remove documentation strings" do
      embed(~w(App.CLI lib/app/cli -fy --skip-docs))
      embed(~w(Other.CLI lib/other/cli -fy --no-moduledoc))

      for path <- Path.wildcard("lib/**/*.ex") do
        refute File.read!(path) =~ ~s(""")
      end

      assert File.read!("lib/other/cli.ex") =~
               "#     mix cli.embed Other.CLI lib/other/cli --force --yes --skip-docs\n"
    end
  end

  describe "cli.embed.check" do
    test "reports up to date embeds" do
      embed(~w(App.CLI lib/app/cli -fy))
      embed(~w(Other.CLI lib/other/cli -fy --extend --skip-docs))

      assert {"lib/app/cli is up to date\nlib/other/cli is up to date", nil} == check()
    end

    test "reports changed, missing and stale files" do
      embed(~w(App.CLI lib/app/cli -fy))
      File.write!("lib/app/cli/option.ex", "# extra\n", [:append])
      File.rm!("lib/app/cli/command.ex")
      File.cp!("lib/app/cli/argument.ex", "lib/app/cli/old.ex")

      assert {output, 1} = check()

      assert output == """
             lib/app/cli is out of date
               missing  lib/app/cli/command.ex
               changed  lib/app/cli/option.ex
               stale    lib/app/cli/old.ex

             Run `mix cli.embed.check --fix` to regenerate 1 embed.\
             """
    end

    test "--fix regenerates out of date embeds and removes stale files" do
      embed(~w(App.CLI lib/app/cli -fy))
      File.write!("lib/app/cli/option.ex", "# extra\n", [:append])
      File.cp!("lib/app/cli/argument.ex", "lib/app/cli/old.ex")

      assert {output, nil} = check(~w(--fix))
      assert output =~ "lib/app/cli: mix cli.embed App.CLI lib/app/cli --force --yes\n"
      assert output =~ "created lib/app/cli/option.ex (overwrite)"
      assert output =~ "removed lib/app/cli/old.ex"
      refute File.exists?("lib/app/cli/old.ex")

      assert {"lib/app/cli is up to date", nil} == check()
    end

    test "accepts banners from previous versions" do
      embed(~w(App.CLI lib/app/cli -fy --extend))

      for path <- Path.wildcard("lib/app/**/*.ex") do
        replace_banner(path, """
        # This file was generated by CliMate. Do not edit this file directly or your
        # changes may be lost.
        #
        # Regenerate the files with the same command:
        #
        #   mix cli.embed App.CLI #{Path.expand("lib/app/cli")} -fy --extend
        #
        """)
      end

      assert {"lib/app/cli is up to date", nil} == check()
    end

    test "limits the check to the given path" do
      embed(~w(App.CLI lib/app/cli -fy))
      embed(~w(Other.CLI lib/other/cli -fy))
      File.rm!("lib/app/cli/command.ex")

      assert {"lib/other/cli is up to date", nil} == check(~w(lib/other/cli))

      assert {output, 1} = check(~w(lib/app/cli))
      assert output =~ "Run `mix cli.embed.check lib/app/cli --fix` to regenerate 1 embed."
    end

    test "fails when no embed is found in the given path" do
      assert {"No embedded CLI found in lib/app/cli", 1} == check(~w(lib/app/cli))
    end

    test "fails on conflicting commands for the same path" do
      embed(~w(App.CLI lib/app/cli -fy))

      replace_banner("lib/app/cli/option.ex", """
      # This file was generated by CliMate.
      #
      #     mix cli.embed App.CLI lib/app/cli --force --yes --skip-docs
      #
      """)

      assert {output, 1} = check()

      assert output == """
             Conflicting commands found for lib/app/cli:

                 mix cli.embed App.CLI lib/app/cli --force --yes
                   lib/app/cli.ex
                   lib/app/cli/argument.ex
                   (6 more files)

                 mix cli.embed App.CLI lib/app/cli --force --yes --skip-docs
                   lib/app/cli/option.ex

             Regenerate each embed with the command you want to keep, then delete the files still listed under other commands.\
             """
    end

    test "reports files left over after switching to --extend as a conflict" do
      embed(~w(App.CLI lib/app/cli -fy))
      embed(~w(App.CLI lib/app/cli -fy --extend))

      assert {output, 1} = check()

      assert output =~
               "    mix cli.embed App.CLI lib/app/cli --force --yes\n      lib/app/cli.ex\n\n"

      File.rm!("lib/app/cli.ex")
      assert {"lib/app/cli is up to date", nil} == check()
    end

    test "--fix with a path only regenerates that embed" do
      embed(~w(App.CLI lib/app/cli -fy))
      embed(~w(Other.CLI lib/other/cli -fy))
      File.rm!("lib/app/cli/command.ex")
      File.rm!("lib/other/cli/command.ex")

      assert {output, nil} = check(~w(lib/app/cli --fix))
      assert output =~ "created lib/app/cli/command.ex"
      refute output =~ "lib/other/cli"

      assert {"lib/app/cli is up to date", nil} == check(~w(lib/app/cli))
      assert {_, 1} = check(~w(lib/other/cli))
    end

    test "accepts the deprecated --no-moduledoc option in banners" do
      embed(~w(App.CLI lib/app/cli -fy --skip-docs))

      for path <- Path.wildcard("lib/app/**/*.ex") do
        replace_banner(path, """
        # This file was generated by CliMate.
        #
        #   mix cli.embed App.CLI lib/app/cli -fy --no-moduledoc
        #
        """)
      end

      assert {output, nil} = check()
      assert output =~ "lib/app/cli is up to date"
    end
  end
end
