version: 2
updates:
  - package-ecosystem: mix
    directory: /
    schedule:
      interval: daily
      time: 02:00
      timezone: Europe/Paris
    open-pull-requests-limit: 1
    groups:
      prod:
        dependency-type: production
      dev:
        dependency-type: development
