defmodule CliMate.Embed do
  @moduledoc false

  @source_root Path.expand("cli", __DIR__)
  @main_source @source_root <> ".ex"

  @banner_first_line ~r/^# This file was generated by CliMate\b/
  @banner_command_line ~r/^#\s*mix cli\.embed\s+(.*)$/

  def config(arguments, options) do
    %{
      prefix: arguments.prefix,
      path: normalize_path(arguments.path),
      extend: options.extend,
      skip_docs: options.skip_docs or not options.moduledoc
    }
  end

  def normalize_path(path) do
    path
    |> Path.expand()
    |> Path.relative_to_cwd()
  end

  def command_line(config) do
    args =
      [config.prefix, config.path, "--force", "--yes"] ++
        if(config.extend, do: ["--extend"], else: []) ++
        if(config.skip_docs, do: ["--skip-docs"], else: [])

    Enum.map_join(["mix", "cli.embed" | args], " ", &quote_arg/1)
  end

  defp quote_arg(arg) do
    if String.match?(arg, ~r/\s/),
      do: inspect(arg),
      else: arg
  end

  def banner_command(content) do
    banner_lines =
      content
      |> String.split("\n")
      |> Enum.take_while(&String.starts_with?(&1, "#"))

    with [first_line | _] <- banner_lines,
         true <- Regex.match?(@banner_first_line, first_line),
         command when is_binary(command) <- find_banner_command(banner_lines) do
      {:ok, command}
    else
      _ -> :error
    end
  end

  defp find_banner_command(banner_lines) do
    Enum.find_value(banner_lines, fn line ->
      case Regex.run(@banner_command_line, line) do
        [_, command] -> String.trim(command)
        nil -> nil
      end
    end)
  end

  def strip_banner(content) do
    content
    |> String.split("\n")
    |> Enum.drop_while(&String.starts_with?(&1, "#"))
    |> Enum.join("\n")
  end

  def generate(config) do
    namespace = config.prefix |> String.split(".") |> Enum.map(&String.to_atom/1)
    main_module = if config.extend, do: namespace ++ [:Base], else: namespace
    alias_replacement = {namespace, main_module}
    banner = banner(config)

    main_target =
      if config.extend,
        do: Path.join(config.path, "base.ex"),
        else: config.path <> ".ex"

    sub_sources =
      for source <- Path.wildcard(Path.join(@source_root, "**/*.ex")) do
        {source, Path.join(config.path, Path.relative_to(source, @source_root))}
      end

    Enum.map([{@main_source, main_target} | sub_sources], fn {source, target} ->
      {format, format_opts} = Mix.Tasks.Format.formatter_for_file(target)
      code = generate_module(File.read!(source), format_opts, alias_replacement, config.skip_docs)
      %{path: target, content: format.(banner <> code)}
    end)
  end

  def write_file!(file) do
    File.mkdir_p!(Path.dirname(file.path))
    File.write!(file.path, file.content)
  end

  defp banner(config) do
    """
    # This file was generated by CliMate v#{version()}. Do not edit this file
    # directly or your changes may be lost.
    #
    # Regenerate the files with:
    #
    #     #{command_line(config)}
    #
    """
  end

  defp version do
    _ = Application.load(:cli_mate)
    Application.spec(:cli_mate, :vsn)
  end

  defp generate_module(source_code, format_opts, alias_replacement, skip_docs?) do
    {forms, comments} =
      Code.string_to_quoted_with_comments!(source_code,
        token_metadata: true,
        literal_encoder: &{:ok, {:__block__, &2, [&1]}},
        unescape: false,
        columns: true
      )

    forms
    |> Macro.postwalk(&replace_aliases(&1, alias_replacement))
    |> Macro.postwalk(&update_docs(&1, skip_docs?, alias_replacement))
    |> Code.quoted_to_algebra(
      [comments: comments, migrate_charlists_as_sigils: true, escape: false] ++
        Keyword.take(format_opts, [:locals_without_parens])
    )
    |> Inspect.Algebra.format(Keyword.get(format_opts, :line_length, 98))
    |> IO.iodata_to_binary()
  end

  defp update_docs({:@, meta, [{attr, attr_meta, [value]}]}, skip_docs?, alias_replacement)
       when attr in [:moduledoc, :doc, :typedoc] do
    value =
      cond do
        not doc_string?(value) -> value
        skip_docs? -> {:__block__, attr_meta, [false]}
        true -> replace_doc_text(value, alias_replacement)
      end

    {:@, meta, [{attr, attr_meta, [value]}]}
  end

  defp update_docs({:@, attr_meta, [{:doc_if_moduledoc, skip_meta, value}]}, true, _)
       when not is_nil(value) do
    {:@, attr_meta, [{:doc_if_moduledoc, skip_meta, [{:__block__, skip_meta, [false]}]}]}
  end

  defp update_docs(form, _, _), do: form

  defp doc_string?({:__block__, _, [text]}), do: is_binary(text)
  defp doc_string?({:<<>>, _, _}), do: true
  defp doc_string?(_), do: false

  defp replace_doc_text({:__block__, meta, [text]}, alias_replacement) do
    {:__block__, meta, [replace_text_aliases(text, alias_replacement)]}
  end

  defp replace_doc_text({:<<>>, meta, parts}, alias_replacement) do
    parts =
      Enum.map(parts, fn
        text when is_binary(text) -> replace_text_aliases(text, alias_replacement)
        interpolation -> interpolation
      end)

    {:<<>>, meta, parts}
  end

  defp replace_text_aliases(text, {namespace_replacement, main_mod_replacement}) do
    Regex.replace(~r/\bCliMate\.CLI((?:\.[A-Z]\w*)*)/, text, fn
      _, "" -> Enum.join(main_mod_replacement, ".")
      _, submodule -> Enum.join(namespace_replacement, ".") <> submodule
    end)
  end

  # replacement of the exact alias
  defp replace_aliases({:__aliases__, meta, [:CliMate, :CLI]}, {_, main_mod_replacement}) do
    {:__aliases__, meta, main_mod_replacement}
  end

  # replacement of submodule
  defp replace_aliases({:__aliases__, meta, [:CliMate, :CLI | rest]}, {namespace_replacement, _}) do
    {:__aliases__, meta, namespace_replacement ++ rest}
  end

  defp replace_aliases(form, _), do: form
end
